#! /bin/bash

# PATH=node_modules/.bin:$PATH

# echo $PATH

# echo "\n\n"
# which ts-node

# ./node_modules/.bin/ts-node --compiler-options "{\"module\": \"commonjs\",\"lib\":[\"es2015\",\"dom\"]}" main.ts

time ts-node --compiler-options "{\"module\": \"commonjs\",\"lib\":[\"es2015\",\"dom\"]}" main.ts $1
