# GitHub Actions workflow for testing and continuous integration.

name: Weekly Continuous Integration Tests

on:
  schedule:
    # run at 6am UTC on Sundays
    - cron: '0 6 * * 7'

jobs:
  ci_tests:
    name: python
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install requests sseclient astropy pytest
    - name: Run tests
      run: |
        cd python
        pytest -v
